id: I09996E89
ocr_import_info:
  timestamp: '2023-06-28T22:36:48.481570+00:00'
  batch_id: batch-08a9
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: PechaJobs
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-06-28 23:42:38.012455+00:00
last_modified: 2023-06-28 23:42:38.012464+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1NLM1577
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1NLM1577
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཟབ་གསང་མཁའ་འགྲོ་སྙིང་ཏིག་གི་བཏགས་གྲོལ་རྒྱུད་དྲུག་པ་རངས་རྗེས་གསུམ་པ་དང་བཅས་པ་སོགས།
  languages:
  - bo
statistics:
  ocr_word_mean_confidence_index: 0.8736409376151691
  ocr_word_median_confidence_index: 0.9485342
bases:
  I1NLM1577_001:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1NLM1577_001
      total_pages: 493
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I1NLM1577_001.txt
    statistics:
      ocr_word_median_confidence_index: 0.9485342
      ocr_word_mean_confidence_index: 0.8736409376151691
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
